### ISSUE TITLE
rebox-cycle: rebox-cycle caught error: (invalid-function rebox-cache) 

### ISSUE THREAD

**Issue by dimbleby** [lewang/rebox2#3]
I see you've been adding options for the stuff I mentioned I needed.  Thank you!  I had expected to struggle with this myself: you'll have certainly done a much better job, and much sooner than I could have done.

However...  if I byte-compile rebox2.el and try doing any refilling, I see the error above.  This doesn't happen if I don't byte-compile - which is therefore an obvious workaround - but I figured you'd probably want to know.

To repro: 

emacs -q rebox2.el
Emacs-Lisp -> byte compile and load
Goto "Hi, I'm a box"
M-x rebox-fill

Cheers

**Comment by lewang** [comment]
Sorry the new features and new entry system is some what in flux, which is why I haven't told you about them yet.

Please try with the latest code.

**Comment by dimbleby** [comment]
I was about to write that this was still broken as at 16fe89c53f57c111fde7d57e52e75da1afa87d54 - does this error not reproduce for you? - but it does appear to be fixed as at 6b5a3f26c800954c4c15003d422fcf3750c11317.
