### ISSUE TITLE
Handling of spaces after periods

### ISSUE THREAD

**Issue by paulprovost** [lewang/rebox2#4]
Hi!

```
Rebox used to leave a space after a trailing period when boxing comments. The current version does not. Maybe you could add that as an option. Just to be clear, currently, we get
```
# Initializations.
# ----------------

where
# Initializations.
# -----------------

would be nice. I find it lets the comments "breathe" a little bit.

Great work otherwise!

**Comment by paulprovost** [comment]
Gah. Hosed by markdown!

**Comment by paulprovost** [comment]
Hi!

Rebox used to leave a space after a trailing period when boxing comments. The current version does not. Maybe you could add that as an option. Just to be clear, currently, we get

```
# Initializations. #
# ---------------- #
```

where

```
# Initializations.  #
# ----------------- #
```

would be nice(r). I find it lets the comments "breathe" a little bit.

Great work otherwise!

**Comment by lewang** [comment]
If it did that then it was a bug ;).  Can you describe the context?  When filling it used to leave a space?

What if you enable the minor-mode?  then spaces at the end automatically expand the box due to autofill.

**Comment by paulprovost** [comment]
I should clarify the "used to" bit. This was using François Pinard's version. I have an older .el version, before the move to pymacs. The latest copyright note on it is 2006.

My issue happens without using the minor mode. This:

```
# Initializations.  #
# ---------------- #
```

formats as this:

```
# Initializations. #
# ---------------- #
```

when hitting "Alt-Q".

With the minor mode active, I am able to hit space after the period and get (what I would like):

```
# Initializations.  #
# ----------------- #
```

Makes sense?

Like I said, I like the extra space after the period. Could you add a flag to enable the "old" behavior?

**Comment by lewang** [comment]
I thought your name looked familiar.  You're from the rebox header?  hehe.

I'll take a look at it.

**Comment by lewang** [comment]
Do the latest changes satisfy your request?

**Comment by paulprovost** [comment]
Yeah, I'm at the origin of this whole thing...

I'll have a look at the changes over the weekend. Thanks!

**Comment by lewang** [comment]
Oh and also if you need a minimum box size, you can se the rebox-min-fill-column

**Comment by paulprovost** [comment]
Great! Setting `rebox-pad-sentence-end` to `t` works fine. Had to set `sentence-end-double-space` to `nil` (two spaces were a bit much). Nice how you used that instead of making up some other sentence end regexp for yourself. I bow to your emacs-lisp talents!
