### ISSUE TITLE
Hi, and thanks! :-)

### ISSUE THREAD

**Issue by pinard** [lewang/rebox2#5]
Le Wang?  Hello!

Not really an "issue" with rebox2.  I just stumbled on rebox2.el today (while looking for boxquote.el, as suggested by someone on the Org mode mailing list), and see you are doing great things with this old code of mine :-).  Thanks for salvaging it!  François

P.S. If you happen to like Python, you might be a bit curious about rebox.py, which is in the contrib/ directory of Pymacs.  But your work likely obsoletes it.  That's very OK!

**Comment by lewang** [comment]
Hi Francois,

Thanks for the note and the very good implementation.  So org-mode is pulling you back into Emacs?  The last i heard, you were leaving us for greener pastures.

**Comment by pinard** [comment]
Le Wang
reply@reply.github.com
writes:

> Thanks for the note and the very good implementation.

Of rebox?  You're generous.  When I translated it from Emacs Lisp to
Python, I noticed a few things I did not like too much.  And after
having translated it, found it a bit slow to initialize (in Python).

When I initially wrote it, I had unexpected difficulties in organizing
the code, it was never neat enough, many iterations have been necessary
before getting an organization that I begin to feel bearable.  I'm glad
you were able to wave and make your way through my mess^H^H^H^Hcode, and
turn it into a much more usable tool.

By the way, the demo video was impressive!  Congratulations.

> So org-mode is pulling you back into Emacs?  The last i heard, you
> were leaving us for greener pastures.

Safer pastures in fact.  Emacs went through a long and dark segment in
its development life.  It recovered somehow, yet not fully.

> Reply to this email directly or view it on GitHub:

May I dare asking for a more direct, non GitHub address to reach you?

Keep happy.  François

**Comment by paulprovost** [comment]
Well, well. Great minds meet again...

**Comment by pinard** [comment]
Hi, Paul!  I hope life is good for you.  Long time no see!  I'm not going downtown much anymore.  Nevertheless, we should share a meal or a beer one of these days!

How did you find about rebox2.el ?  I really stumble on it by an accident of luck! :-)

Emacs Org mode brought me back to Emacs, for many things.  It's worth a good look, if you happen to like organisational methods.  Le Wang is also an Org mode user, and I vaguely see some influence from Org mode in the design of rebox2.  (but I may be dreaming this).

François

**Comment by paulprovost** [comment]
Hi François. I found it through the Emacs Wiki. I was having issues with the pymacs version, and was looking for an older elisp one. Then I happened on Le Wang's version. I'm happily reboxing again.

Org mode is pure genius. I use it heavily at both home and work.

**Comment by pinard** [comment]
paulprovost
reply@reply.github.com
writes:

> I'm happily reboxing again.

:-)

> Org mode is pure genius. I use it heavily at both home and work.

:-) :-)

François
